### ISSUE TITLE
arrayname and site bug

### ISSUE THREAD

**Issue by ptiede** [Smithsonian/ngehtsim#3]
First issue!

There seems to be an issue when you specify the sites in the yamlfile but you don't include the arrayname. For example,

```yaml
# array: 

# list containing the array site names
sites: ['LMT','BAJA','CNI','HAY','LAS','OVRO','JCMT','SMT','GLT','APEX','GARS','GAM','CAT','BOL','BRZ','PIKE']
```
creates very sparse coverage at 345 GHz, while

```yaml
array: 

# list containing the array site names
sites: ['LMT','BAJA','CNI','HAY','LAS','OVRO','JCMT','SMT','GLT','APEX','GARS','GAM','CAT','BOL','BRZ','PIKE']
```

works fine.
